changelog:
  exclude:
    labels:
      - release

  categories:
    - title: Features
      labels:
        - feature
    - title: Enhancements
      labels:
        - enhancement
    - title: Fixes
      labels:
        - fix
    - title: Documents
      labels:
        - document
    - title: Dependencies
      labels:
        - dependency

    - title: Other Changes
      labels:
        - "*"
