name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
            cmake -B build -DDEVELOP=1
            cmake --build build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install package
        run: |
          sudo apt-get install gnuplot

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build

      - name: Run unit test
        run: |
            chmod +x ./build/signal_processing_test
            ctest --test-dir build

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reviewdog
        uses: reviewdog/action-cpplint@a363bae6972f0ee08a269272eaa549453a531c2a
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Reviewdog
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
